
services:
  postgres:
    image: postgres:15.4
    container_name: postgres_15.4
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=spring-appointments