spring:
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/spring-appointments
  data:
    rest:
      base-path: /api
      detection-strategy: annotated
  liquibase:
    change-log: classpath:database/root.xml