spring:
  datasource:
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    url: ${SPRING_DATASOURCE_URL}
  data:
    rest:
      base-path: /api
      detection-strategy: annotated
      default-page-size: 5
      max-page-size: 100
  liquibase:
    change-log: classpath:database/root.xml